---
title: "PenalizedModels"
author: "Darren"
output: html_document
---

## title: "Penalized Regression Models (Lasso & Ridge)" author: "Darren" output: html\_document: toc: true toc\_depth: 2

```{r libr}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
# Libraries
library(tidyverse)
library(caret)
library(glmnet)
library(pROC)
```

## 1. Load Data and Prepare Matrices

```{r  load}
processed_path <- "processed_data"
df_bal <- readRDS(file.path(processed_path, "heart_disease_cleaned.rds"))
set.seed(2025)
train_idx <- createDataPartition(df_bal$num, p = 0.8, list = FALSE)
train <- df_bal[train_idx, ]
test  <- df_bal[-train_idx, ]

# Create model matrix (no intercept)
x_train <- model.matrix(num ~ . -1, data = train)
y_train <- as.numeric(as.character(train$num))
x_test  <- model.matrix(num ~ . -1, data = test)
y_test  <- as.numeric(as.character(test$num))
```



## 2. Lasso (L1) Regression

```{r lasso}
set.seed(2025)
cv_lasso <- cv.glmnet(
  x_train, y_train,
  alpha = 1,           # Lasso penalty
  family = "binomial",
  type.measure = "auc",
  nfolds = 5
)
# Best lambda
lambda_lasso <- cv_lasso$lambda.min
# Fit final model
lasso_mod <- glmnet(
  x_train, y_train,
  alpha = 1,
  family = "binomial",
  lambda = lambda_lasso
)

# Coefficients
coef_lasso <- coef(lasso_mod)
print(coef_lasso)

# Plot CV curve
plot(cv_lasso)
```

## 3. Ridge (L2) Regression

```{r ridge}
set.seed(2025)
cv_ridge <- cv.glmnet(
  x_train, y_train,
  alpha = 0,           # Ridge penalty
  family = "binomial",
  type.measure = "auc",
  nfolds = 5
)
lambda_ridge <- cv_ridge$lambda.min
ridge_mod <- glmnet(
  x_train, y_train,
  alpha = 0,
  family = "binomial",
  lambda = lambda_ridge
)

coef_ridge <- coef(ridge_mod)
print(coef_ridge)

# Plot CV curve
plot(cv_ridge)
```

## 4. Model Performance Comparison

```{r penalized predictions}
# Predictions
prob_lasso <- predict(lasso_mod, x_test, type = "response")[,1]
prob_ridge <- predict(ridge_mod, x_test, type = "response")[,1]

# ROC
roc_lasso <- roc(test$num, prob_lasso)
roc_ridge <- roc(test$num, prob_ridge)

# AUC
auc_vals <- tibble(
  Model = c("Lasso", "Ridge"),
  AUC = c(auc(roc_lasso), auc(roc_ridge))
)
knitr::kable(auc_vals, caption = "AUC for Lasso vs Ridge")

# Plot ROC curves
plot(roc_lasso, col="blue", main="ROC: Lasso vs Ridge")
lines(roc_ridge, col="red")
legend("bottomright", legend = c("Lasso","Ridge"), col = c("blue","red"), lwd=2)
```

## 5. Variable Importance via Lasso Coefficients

```{r VARIMP_Penalized}
# Extract non-zero coefficients
df_coef <- as.data.frame(as.matrix(coef_lasso)) %>%
  rownames_to_column(var = "Feature") %>%
  rename(Coefficient = s1) %>%
  filter(Coefficient != 0)

df_coef %>%
  arrange(desc(abs(Coefficient))) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(Feature, Coefficient), y = Coefficient)) +
    geom_col(fill = "steelblue") +
    coord_flip() +
    labs(title = "Top 10 Lasso-selected Features", x = "Feature", y = "Coefficient")
```

## 6. Save Models

```{r save_penalized_Models}
dir.create("models", showWarnings = FALSE)
saveRDS(lasso_mod, "models/lasso_model.rds")
saveRDS(ridge_mod, "models/ridge_model.rds")
```
