---
title: "raw_valb_EDA"
output: html_document
date: "2025-06-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


## Importing Libraries

```{r libraries}
library(tidyverse)
library(ggplot2)
library(corrplot)
library(readr)
library(dplyr)
```

## Importing Data

```{r data}
va_lb_raw <- read.csv("../Data/Raw/long-beach-va.data",
                      header = FALSE)

dim(va_lb_raw)
```

the data is in one variable, with "name" being the separator
```{r}
full_cols <- c(
  "id",       # 1. patient ID
  "ccf",      # 2. ccf (social security #; now dummy)
  "age",      # 3. age in years
  "sex",      # 4. sex (1=male; 0=female)
  "painloc",  # 5. chest pain location (1=substernal; 0=otherwise)
  "painexer", # 6. provoked by exertion (1=yes; 0=no)
  "relrest",  # 7. relieved after rest (1=yes; 0=no)
  "pncaden",  # 8. sum of 5, 6, and 7
  "cp",       # 9. chest pain type (1–4)
  "trestbps", # 10. resting blood pressure (mm Hg)
  "htn",      # 11. history of hypertension (1=yes; 0=no)
  "chol",     # 12. serum cholesterol (mg/dL)
  "smoke",    # 13. is a smoker (1=yes; 0=no)
  "cigs",     # 14. cigarettes per day
  "years",    # 15. years as a smoker
  "fbs",      # 16. fasting blood sugar > 120 mg/dL (1=yes; 0=no)
  "dm",       # 17. diabetes history (1=yes; 0=no)
  "famhist",  # 18. family history of CAD (1=yes; 0=no)
  "restecg",  # 19. resting ECG results (0–2)
  "ekgmo",    # 20. month of exercise ECG reading
  "ekgday",   # 21. day of exercise ECG reading
  "ekgyr",    # 22. year of exercise ECG reading
  "dig",      # 23. digitalis used during ECG (1=yes; 0=no)
  "prop",     # 24. beta blocker used (1=yes; 0=no)
  "nitr",     # 25. nitrates used (1=yes; 0=no)
  "pro",      # 26. calcium channel blocker used (1=yes; 0=no)
  "diuretic", # 27. diuretic used during ECG (1=yes; 0=no)
  "proto",    # 28. exercise protocol (1=Bruce, 2=Kottus, … 12=arm ergometer)
  "thaldur",  # 29. duration of exercise test (minutes)
  "thaltime", # 30. time when ST depression was noted
  "met",      # 31. mets achieved
  "thalach",  # 32. maximum heart rate achieved
  "thalrest", # 33. resting heart rate
  "tpeakbps", # 34. peak exercise BP (first part)
  "tpeakbpd", # 35. peak exercise BP (second part)
  "dummy",    # 36. (unused)
  "trestbpd", # 37. resting blood pressure (duplicate)
  "exang",    # 38. exercise‐induced angina (1=yes; 0=no)
  "xhypo",    # 39. (1=yes; 0=no)
  "oldpeak",  # 40. ST depression relative to rest
  "slope",    # 41. slope of the peak exercise ST segment (1–3)
  "rldv5",    # 42. height at rest
  "rldv5e",   # 43. height at peak exercise
  "ca",       # 44. number of major vessels (0–3) seen on fluoroscopy
  "restckm",  # 45. irrelevant
  "exerckm",  # 46. irrelevant
  "restef",   # 47. rest radionuclide ejection fraction
  "restwm",   # 48. rest wall motion abnormality (0–3)
  "exeref",   # 49. exercise radionuclide ejection fraction
  "exerwm",   # 50. exercise wall motion (0–3)
  "thal",     # 51. thalassemia (3=normal; 6=fixed; 7=reversible)
  "thalsev",  # 52. not used
  "thalpul",  # 53. not used
  "earlobe",  # 54. not used
  "cmo",      # 55. month of cardiac cath
  "cday",     # 56. day of cardiac cath
  "cyr",      # 57. year of cardiac cath
  "num",      # 58. diagnosis (0–4)
  "lmt",      # 59. left main coronary artery
  "ladprox",  # 60. left anterior descending proximal
  "laddist",  # 61. left anterior descending distal
  "diag",     # 62. diagonal
  "cxmain",   # 63. circumflex main
  "ramus",    # 64. ramus
  "om1",      # 65. obtuse marginal 1
  "om2",      # 66. obtuse marginal 2
  "rcaprox",  # 67. right coronary artery proximal
  "rcadist",  # 68. right coronary artery distal
  "lvx1",     # 69. not used
  "lvx2",     # 70. not used
  "lvx3",     # 71. not used
  "lvx4",     # 72. not used
  "lvf",      # 73. not used
  "cathef",   # 74. not used
  "junk",     # 75. not used
  "name"      # 76. last name (dummy string)
)

```

## Initial EDA

```{r EDA}

```
